name: pyeafe
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics=2019.1.0
  - fenics-dolfin=2019.1.0
  - numpy=1.20.0
  - python=3.8.5
  # dev-dependencies
  - black=19.10
  - flake8=3.8.4
  - pre-commit=2.10.0
  - pytest=6.2.2
